version: '3'
services:
  mysql:
    container_name: mysql
    image: "mysql:5.7.20"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=shiye1805A
      - MYSQL_DATABASE=db_seeyii
    restart: on-failure
    volumes:
      - ./_db:/var/lib/mysql
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    #      - ./my.cnf:/etc/mysql/my.cnf
      - ./conf:/etc/mysql/conf.d
      - ./logs:/var/log/mysql
#      - ./binlog:/var/lib/mysql/mysql-bin
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    networks:
      - app_net

networks:
  app_net: