FROM hugojuhel/notebook:latest

RUN pip install keras tensorflow pillow h5py jupyter scikit-image \ 
&& git clone https://github.com/emilwallner/Coloring-greyscale-images \ 
&& cd Coloring-greyscale-images
#&& jupyter notebook



CMD ["jupyter","notebook"]